Importing Necessary Libraries:


In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

### Reading the Data:

In [46]:
df = pd.read_csv('data.csv')

### Visulaizing the Data:

In [47]:
df.shape

(569, 5)

In [48]:
df.head()

radius_mean  texture_mean  perimeter_mean  area_mean diagnosis
0        17.99         10.38          122.80     1001.0         M
1        20.57         17.77          132.90     1326.0         M
2        19.69         21.25          130.00     1203.0         M
3        11.42         20.38           77.58      386.1         M
4        20.29         14.34          135.10     1297.0         M

### Defining the features and the Target:

In [49]:
X = df.drop('diagnosis', axis = 1)
Y = df['diagnosis']

In [50]:
X

radius_mean  texture_mean  perimeter_mean  area_mean
0         17.990         10.38          122.80     1001.0
1         20.570         17.77          132.90     1326.0
2         19.690         21.25          130.00     1203.0
3         11.420         20.38           77.58      386.1
4         20.290         14.34          135.10     1297.0
5         12.450         15.70           82.57      477.1
6         18.250         19.98          119.60     1040.0
7         13.710         20.83           90.20      577.9
8         13.000         21.82           87.50      519.8
9         12.460         24.04           83.97      475.9
10        16.020         23.24          102.70      797.8
11        15.780         17.89          103.60      781.0
12        19.170         24.80          132.40     1123.0
13        15.850         23.95          103.70      782.7
14        13.730         22.61           93.60      578.3
15        14.540         27.54           96.73      658.8
16        14.680         20.13           94.74      684.5
17        16.130         20.68          108.10      798.8
18        19.810         22.15          130.00     1260.0
19        13.540         14.36           87.46      566.3
20        13.080         15.71           85.63      520.0
21         9.504         12.44           60.34      273.9
22        15.340         14.26          102.50      704.4
23        21.160         23.04          137.20     1404.0
24        16.650         21.38          110.00      904.6
25        17.140         16.40          116.00      912.7
26        14.580         21.53           97.41      644.8
27        18.610         20.25          122.10     1094.0
28        15.300         25.27          102.40      732.4
29        17.570         15.05          115.00      955.1
..           ...           ...             ...        ...
539        7.691         25.44           48.34      170.4
540       11.540         14.44           74.65      402.9
541       14.470         24.99           95.81      656.4
542       14.740         25.42           94.70      668.6
543       13.210         28.06           84.88      538.4
544       13.870         20.70           89.77      584.8
545       13.620         23.23           87.19      573.2
546       10.320         16.35           65.31      324.9
547       10.260         16.58           65.85      320.8
548        9.683         19.34           61.05      285.7
549       10.820         24.21           68.89      361.6
550       10.860         21.48           68.51      360.5
551       11.130         22.44           71.49      378.4
552       12.770         29.43           81.35      507.9
553        9.333         21.94           59.01      264.0
554       12.880         28.92           82.50      514.3
555       10.290         27.61           65.67      321.4
556       10.160         19.59           64.73      311.7
557        9.423         27.88           59.26      271.3
558       14.590         22.68           96.39      657.1
559       11.510         23.93           74.52      403.5
560       14.050         27.15           91.38      600.4
561       11.200         29.37           70.67      386.0
562       15.220         30.62          103.40      716.9
563       20.920         25.09          143.00     1347.0
564       21.560         22.39          142.00     1479.0
565       20.130         28.25          131.20     1261.0
566       16.600         28.08          108.30      858.1
567       20.600         29.33          140.10     1265.0
568        7.760         24.54           47.92      181.0

[569 rows x 4 columns]

In [51]:
Y

0      M
1      M
2      M
3      M
4      M
5      M
6      M
7      M
8      M
9      M
10     M
11     M
12     M
13     M
14     M
15     M
16     M
17     M
18     M
19     B
20     B
21     B
22     M
23     M
24     M
25     M
26     M
27     M
28     M
29     M
      ..
539    B
540    B
541    B
542    B
543    B
544    B
545    B
546    B
547    B
548    B
549    B
550    B
551    B
552    B
553    B
554    B
555    B
556    B
557    B
558    B
559    B
560    B
561    B
562    M
563    M
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

### Splitting the data into train data and test data:

In [52]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.20)

In [53]:
from sklearn.svm import SVC
model = SVC(kernel = 'linear')
model.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [54]:
"""Predicting Values Using SVM algorithm Model"""
y_pred = model.predict(X_test)
y_pred

array(['B', 'B', 'M', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'M', 'B',
       'M', 'B', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M',
       'B', 'M', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'M', 'B', 'B',
       'B', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B',
       'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M',
       'B', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M',
       'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M',
       'M', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B'], dtype=object)

### Evalutaion from SVM model:

In [55]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))

[[75  4]
 [ 5 30]]
             precision    recall  f1-score   support

          B       0.94      0.95      0.94        79
          M       0.88      0.86      0.87        35

avg / total       0.92      0.92      0.92       114



### Implementing Kernel SVM with Sklearn SVM module:

#### Polynomial Kernel: 

In [58]:
from sklearn.svm import SVC
model1 = SVC(kernel='poly', degree=8)
model1.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [60]:
y_pred1 = model1.predict(X_test)
y_pred1

array(['M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M'], dtype=object)

#### Gaussian Kernel:

In [62]:
model2 = SVC(kernel='rbf')
model2.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [64]:
y_pred2 = model2.predict(X_test)
y_pred2

array(['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B'], dtype=object)

In [65]:
print(confusion_matrix(Y_test, y_pred2))
print(classification_report(Y_test, y_pred2))

[[78  1]
 [32  3]]
             precision    recall  f1-score   support

          B       0.71      0.99      0.83        79
          M       0.75      0.09      0.15        35

avg / total       0.72      0.71      0.62       114



#### Sigmoid Kernel: 

In [66]:
model3 = SVC(kernel='sigmoid')
model3.fit(X_train, Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [68]:
y_pred3 = model3.predict(X_test)
y_pred3

array(['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B'], dtype=object)

In [70]:
print(confusion_matrix(Y_test, y_pred3 ))
print(classification_report(Y_test, y_pred3))

[[79  0]
 [35  0]]
             precision    recall  f1-score   support

          B       0.69      1.00      0.82        79
          M       0.00      0.00      0.00        35

avg / total       0.48      0.69      0.57       114



C:\Users\Geekquad\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
